export async function seedLogs(supabase, userId) {
  const d = (iso) => new Date(iso).getTime()

  const logs = [
    {
      id: String(d('2026-06-17T07:23:00')),
      symptom: 'silent acid reflux',
      timestamp: d('2026-06-17T07:23:00'),
      onset_category: 'a few hours ago',
      summary: 'Symptom: Silent acid reflux, Started: Morning (7:23am), Severity: 3/5, Context: Coffee on empty stomach, skipped breakfast, poor sleep (2/5)',
      messages: [
        { role: 'user', content: 'silent acid reflux' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '3 out of 5' },
        { role: 'assistant', content: 'Woke up early — did you have coffee before eating anything?' },
        { role: 'user', content: 'Yes, black coffee around 6:30, nothing else' },
        { role: 'assistant', content: 'Sleep quality last night? 1–5?' },
        { role: 'user', content: '2 out of 5' },
        { role: 'assistant', content: 'Anything else you think might be related? Even a small thing.' },
        { role: 'user', content: "Skipped breakfast entirely, just wasn't hungry" },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Silent acid reflux' }, { label: 'Started', value: 'Morning (7:23am)' }, { label: 'Severity', value: '3/5' }, { label: 'Context', value: 'Coffee on empty stomach, skipped breakfast, poor sleep (2/5)' }], note: 'Starting the day with coffee before food is a common trigger — even a few crackers before your first cup could help settle things.' } },
      ],
    },
    {
      id: String(d('2026-05-15T06:45:00')),
      symptom: 'ear feels blocked',
      timestamp: d('2026-05-15T06:45:00'),
      onset_category: 'just_now',
      summary: 'Symptom: Ear feels blocked, Started: Morning (6:45am), Severity: 2/5, Context: Left ear muffled, poor sleep (2/5), 2 coffees on empty stomach',
      messages: [
        { role: 'user', content: 'ear feels blocked' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '2 out of 5' },
        { role: 'assistant', content: "One ear or both — and does it feel like pressure, muffled hearing, or a flutter?" },
        { role: 'user', content: "Left ear, muffled — like I'm underwater" },
        { role: 'assistant', content: 'Sleep last night? 1–5?' },
        { role: 'user', content: '2 out of 5' },
        { role: 'assistant', content: 'Anything else that might be related?' },
        { role: 'user', content: "Two coffees already, hadn't eaten anything yet" },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Ear feels blocked' }, { label: 'Started', value: 'Morning (6:45am)' }, { label: 'Severity', value: '2/5' }, { label: 'Context', value: 'Left ear muffled, poor sleep (2/5), 2 coffees on empty stomach' }], note: 'Ear congestion and acid often travel together — your body may be signaling it needs more rest and a gentler morning routine.' } },
      ],
    },
    {
      id: String(d('2026-05-13T08:30:00')),
      symptom: 'fatigue',
      timestamp: d('2026-05-13T08:30:00'),
      onset_category: 'just_now',
      summary: 'Symptom: Fatigue, Started: Morning, Severity: 3/5, Context: Fragmented sleep (5.5h), skipped breakfast, high work stress, caffeine only',
      messages: [
        { role: 'user', content: 'fatigue' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '3 out of 5' },
        { role: 'assistant', content: 'How many hours of sleep did you get, and did you wake up during the night?' },
        { role: 'user', content: 'About 5.5 hours, kept waking up' },
        { role: 'assistant', content: "Have you eaten this morning or just had coffee?" },
        { role: 'user', content: "Just coffee, haven't eaten yet" },
        { role: 'assistant', content: 'Anything else you think might be related? Even a small thing.' },
        { role: 'user', content: 'Stressful week, been on back-to-back calls since 8am' },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Fatigue' }, { label: 'Started', value: 'Morning' }, { label: 'Severity', value: '3/5' }, { label: 'Context', value: 'Fragmented sleep (5.5h), no breakfast yet, work stress, caffeine only' }], note: 'Fatigue on top of fragmented sleep and no food can compound quickly — try a short break and something to eat before your next call.' } },
      ],
    },
    {
      id: String(d('2026-05-11T07:00:00')),
      symptom: 'silent acid reflux',
      timestamp: d('2026-05-11T07:00:00'),
      onset_category: 'just_now',
      summary: 'Symptom: Silent acid reflux, Started: Morning (7am), Severity: 4/5, Context: Late dinner (10pm) with wine, poor sleep (2/5), ear pressure on waking',
      messages: [
        { role: 'user', content: 'silent acid reflux' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '4 out of 5' },
        { role: 'assistant', content: 'Morning episode — did you eat late last night or have anything acidic?' },
        { role: 'user', content: 'Big dinner around 10pm with wine' },
        { role: 'assistant', content: 'How was your sleep? 1–5?' },
        { role: 'user', content: '2 out of 5' },
        { role: 'assistant', content: 'Anything else that might be related?' },
        { role: 'user', content: 'Woke up with ear pressure too, felt heavy all morning' },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Silent acid reflux' }, { label: 'Started', value: 'Morning (7am)' }, { label: 'Severity', value: '4/5' }, { label: 'Context', value: 'Late dinner (10pm) with wine, poor sleep (2/5), ear pressure on waking' }], note: 'Late heavy meals with alcohol before lying down are a strong reflux combination — an earlier dinner could make a noticeable difference.' } },
      ],
    },
    {
      id: String(d('2026-05-09T14:00:00')),
      symptom: 'brain fog',
      timestamp: d('2026-05-09T14:00:00'),
      onset_category: 'hours_ago',
      summary: 'Symptom: Brain fog, Started: Mid-morning (worsening by 2pm), Severity: 2/5, Context: Low hydration (1 glass), continuous screen time since 9am, caffeine-heavy day',
      messages: [
        { role: 'user', content: 'brain fog' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '2 out of 5' },
        { role: 'assistant', content: 'Did this come on gradually or was it there when you woke up?' },
        { role: 'user', content: 'Started around 11am, getting worse now' },
        { role: 'assistant', content: 'How much water have you had today?' },
        { role: 'user', content: 'Just one glass I think, mostly coffee' },
        { role: 'assistant', content: 'Anything else you think might be related?' },
        { role: 'user', content: "Been staring at screens since 9am with no real break" },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Brain fog' }, { label: 'Started', value: 'Mid-morning (worsening by 2pm)' }, { label: 'Severity', value: '2/5' }, { label: 'Context', value: 'Low hydration (1 glass), continuous screen time since 9am, caffeine-heavy day' }], note: 'Brain fog from dehydration and screen fatigue often responds quickly to water and a short walk — worth trying before your next task.' } },
      ],
    },
    {
      id: String(d('2026-05-05T10:00:00')),
      symptom: 'travel fatigue',
      timestamp: d('2026-05-05T10:00:00'),
      onset_category: 'earlier_today',
      summary: 'Symptom: Travel fatigue, Started: 3 days post-arrival, Severity: 4/5, Context: 10h flight / 8hr time zone shift, sleep 3/5 (early waking), persistent body heaviness',
      messages: [
        { role: 'user', content: 'travel fatigue' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '4 out of 5' },
        { role: 'assistant', content: 'When did you arrive, and how many time zones did you cross?' },
        { role: 'user', content: 'Arrived 3 days ago from a 10-hour flight, about 8 hours ahead' },
        { role: 'assistant', content: 'How has sleep been since arriving? 1–5?' },
        { role: 'user', content: '3 out of 5 — falling asleep okay but waking early' },
        { role: 'assistant', content: 'Anything else you think might be related?' },
        { role: 'user', content: 'Body still feels heavy and sluggish even though sleep was okay' },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Travel fatigue' }, { label: 'Started', value: '3 days post-arrival' }, { label: 'Severity', value: '4/5' }, { label: 'Context', value: '10h flight / 8hr time zone shift, sleep 3/5 (early waking), body heaviness and sluggishness persisting' }], note: 'Post-travel fatigue often lingers 3–5 days even when sleep improves — light movement and staying hydrated can help your body readjust faster.' } },
      ],
    },
    {
      id: String(d('2026-05-03T07:30:00')),
      symptom: 'ear feels blocked',
      timestamp: d('2026-05-03T07:30:00'),
      onset_category: 'just_now',
      summary: 'Symptom: Ear feels blocked, Started: Morning (7:30am), Severity: 3/5, Context: Throat fullness sensation, poor sleep (2/5), coffee before food, recurring morning pattern',
      messages: [
        { role: 'user', content: 'ear feels blocked' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '3 out of 5' },
        { role: 'assistant', content: 'Is there a throat sensation too — like something stuck or needing to swallow?' },
        { role: 'user', content: 'Yes, kind of like something stuck in my throat' },
        { role: 'assistant', content: 'Sleep last night, and did you have coffee before eating?' },
        { role: 'user', content: 'Sleep was poor, maybe 2/5. Coffee before anything as usual.' },
        { role: 'assistant', content: 'Anything else that might be related?' },
        { role: 'user', content: 'This keeps happening in the morning lately' },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Ear feels blocked' }, { label: 'Started', value: 'Morning (7:30am)' }, { label: 'Severity', value: '3/5' }, { label: 'Context', value: 'Throat fullness sensation, poor sleep (2/5), coffee before food, recurring morning pattern' }], note: 'The throat and ear fullness combination is often a silent reflux sign — the recurring morning pattern with coffee on an empty stomach is worth addressing.' } },
      ],
    },
    {
      id: String(d('2026-05-01T20:00:00')),
      symptom: 'anxiety',
      timestamp: d('2026-05-01T20:00:00'),
      onset_category: 'earlier_today',
      summary: 'Symptom: Anxiety, Started: Evening, Severity: 3/5, Context: Racing thoughts, chest tightness, poor sleep this week (2/5), high caffeine intake, heavy workload',
      messages: [
        { role: 'user', content: 'anxiety' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '3 out of 5' },
        { role: 'assistant', content: 'More of a low-level tension, or physical — racing thoughts, tight chest?' },
        { role: 'user', content: "Racing thoughts and chest tightness, hard to unwind" },
        { role: 'assistant', content: 'How has sleep been this week? 1–5?' },
        { role: 'user', content: "2 out of 5, mind doesn't stop at night" },
        { role: 'assistant', content: 'Anything else you think might be related?' },
        { role: 'user', content: "Work has been really heavy and I've been drinking a lot of coffee to get through it" },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Anxiety' }, { label: 'Started', value: 'Evening' }, { label: 'Severity', value: '3/5' }, { label: 'Context', value: 'Racing thoughts, chest tightness, poor sleep this week (2/5), high caffeine intake, heavy workload' }], note: 'Caffeine amplifies anxiety and disrupts sleep, which then increases anxiety — cutting off coffee by noon might help break the cycle.' } },
      ],
    },
    {
      id: String(d('2026-04-29T12:30:00')),
      symptom: 'acid reflux — chest tightness',
      timestamp: d('2026-04-29T12:30:00'),
      onset_category: 'hours_ago',
      summary: 'Symptom: Acid reflux — chest tightness, Started: Midday (12:30pm), Severity: 2/5, Context: Matcha on empty stomach (~1hr before), stress 3/5, skipped lunch',
      messages: [
        { role: 'user', content: 'acid reflux — chest tightness' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '2 out of 5' },
        { role: 'assistant', content: 'Midday episode — what did you have this morning?' },
        { role: 'user', content: 'Had matcha about an hour ago, nothing else yet' },
        { role: 'assistant', content: 'Stress level today? 1–5?' },
        { role: 'user', content: '3 out of 5' },
        { role: 'assistant', content: 'Anything else you think might be related?' },
        { role: 'user', content: "Didn't eat lunch, just the matcha" },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Acid reflux — chest tightness' }, { label: 'Started', value: 'Midday (12:30pm)' }, { label: 'Severity', value: '2/5' }, { label: 'Context', value: 'Matcha on empty stomach (~1hr before), stress 3/5, skipped lunch' }], note: 'Matcha is acidic and can trigger reflux on an empty stomach, similar to coffee — pairing it with even a light snack could prevent this.' } },
      ],
    },
    {
      id: String(d('2026-04-27T09:00:00')),
      symptom: 'travel fatigue',
      timestamp: d('2026-04-27T09:00:00'),
      onset_category: 'earlier_today',
      summary: 'Symptom: Travel fatigue, Started: 3 days post-return, Severity: 3/5, Context: 12h trip / 6hr time zone, sleep 3/5, body heaviness, low motivation',
      messages: [
        { role: 'user', content: 'travel fatigue' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '3 out of 5' },
        { role: 'assistant', content: 'When did you get back, and how far did you travel?' },
        { role: 'user', content: "Got back 3 days ago from a 12-hour trip, 6-hour time difference" },
        { role: 'assistant', content: 'Sleep since you got back — 1–5?' },
        { role: 'user', content: "3 out of 5, sleeping okay but body doesn't feel right" },
        { role: 'assistant', content: 'Anything else that might be related?' },
        { role: 'user', content: 'Just feel heavy and unmotivated, energy is lower than usual' },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Travel fatigue' }, { label: 'Started', value: '3 days post-return' }, { label: 'Severity', value: '3/5' }, { label: 'Context', value: '12h trip / 6hr time zone, sleep 3/5, body heaviness, low motivation' }], note: 'Return jet lag often hits differently than outbound — your body is still syncing up even when the sleep feels okay.' } },
      ],
    },
    {
      id: String(d('2026-04-26T15:00:00')),
      symptom: 'fatigue',
      timestamp: d('2026-04-26T15:00:00'),
      onset_category: 'earlier_today',
      summary: 'Symptom: Fatigue, Started: Afternoon, Severity: 3/5, Context: Low energy and poor focus, low hydration (~2 glasses), 5h sleep, stressful morning meeting',
      messages: [
        { role: 'user', content: 'fatigue' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '3 out of 5' },
        { role: 'assistant', content: "Is this sleepy-heavy fatigue or more of a low-energy / can't-focus feeling?" },
        { role: 'user', content: 'More low energy, can barely focus' },
        { role: 'assistant', content: 'How much water have you had today?' },
        { role: 'user', content: 'Maybe two glasses, not much' },
        { role: 'assistant', content: 'Anything else you think might be related?' },
        { role: 'user', content: "Didn't sleep well — maybe 5 hours — and had a stressful meeting this morning" },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Fatigue' }, { label: 'Started', value: 'Afternoon' }, { label: 'Severity', value: '3/5' }, { label: 'Context', value: 'Low energy and poor focus, low hydration (~2 glasses), 5h sleep, stressful morning meeting' }], note: 'Poor sleep and low hydration together are a reliable fatigue combination — even a glass of water now and a short pause could help.' } },
      ],
    },
    {
      id: String(d('2026-04-24T11:00:00')),
      symptom: 'brain fog',
      timestamp: d('2026-04-24T11:00:00'),
      onset_category: 'hours_ago',
      summary: 'Symptom: Brain fog, Started: Mid-morning, Severity: 3/5, Context: Poor sleep (5h, interrupted), continuous screen time since 8am, low hydration, coffee only',
      messages: [
        { role: 'user', content: 'brain fog' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '3 out of 5' },
        { role: 'assistant', content: 'How was sleep last night — hours and quality?' },
        { role: 'user', content: 'About 5 hours, woke up a few times' },
        { role: 'assistant', content: 'Have you been on screens a lot since waking?' },
        { role: 'user', content: 'Yeah, on my laptop since 8am with no break' },
        { role: 'assistant', content: 'Anything else that might be related?' },
        { role: 'user', content: "Haven't drunk anything except coffee" },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Brain fog' }, { label: 'Started', value: 'Mid-morning' }, { label: 'Severity', value: '3/5' }, { label: 'Context', value: 'Poor sleep (5h, interrupted), continuous screen time since 8am, low hydration, coffee only' }], note: 'All three fog contributors today: sleep debt, screen time, and dehydration — even a short break and a glass of water can lift this.' } },
      ],
    },
    {
      id: String(d('2026-04-23T07:00:00')),
      symptom: 'ear feels blocked',
      timestamp: d('2026-04-23T07:00:00'),
      onset_category: 'just_now',
      summary: 'Symptom: Ear feels blocked, Started: Morning (7am), Severity: 2/5, Context: Right ear fullness, poor sleep (2/5), coffee before food, recurring pattern on low-sleep mornings',
      messages: [
        { role: 'user', content: 'ear feels blocked' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '2 out of 5' },
        { role: 'assistant', content: 'One ear or both, and any pain or just fullness?' },
        { role: 'user', content: 'Just right ear, no pain — just feels full' },
        { role: 'assistant', content: 'Sleep last night and coffee this morning?' },
        { role: 'user', content: 'Sleep was bad, 2/5. Coffee before anything else.' },
        { role: 'assistant', content: 'Anything else that might be related?' },
        { role: 'user', content: 'Feels like the same thing that happens on bad sleep mornings' },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Ear feels blocked' }, { label: 'Started', value: 'Morning (7am)' }, { label: 'Severity', value: '2/5' }, { label: 'Context', value: 'Right ear fullness, poor sleep (2/5), coffee before food, recurring pattern on low-sleep mornings' }], note: 'The pattern of poor sleep → morning coffee → ear pressure is worth tracking — it may point to silent reflux reaching the upper airway.' } },
      ],
    },
    {
      id: String(d('2026-04-22T07:30:00')),
      symptom: 'silent acid reflux',
      timestamp: d('2026-04-22T07:30:00'),
      onset_category: 'just_now',
      summary: 'Symptom: Silent acid reflux, Started: Morning (7:30am), Severity: 2/5, Context: Poor sleep (2/5), dinner at 9pm, coffee before food, low energy',
      messages: [
        { role: 'user', content: 'silent acid reflux' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '2 out of 5' },
        { role: 'assistant', content: 'Morning episode — how was sleep, and what time was your last meal yesterday?' },
        { role: 'user', content: 'Sleep was 2/5. Dinner around 9pm, nothing too heavy.' },
        { role: 'assistant', content: 'Coffee before eating today?' },
        { role: 'user', content: 'Yes, first thing as always' },
        { role: 'assistant', content: 'Anything else you think might be related?' },
        { role: 'user', content: 'Low energy too, feeling off generally' },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Silent acid reflux' }, { label: 'Started', value: 'Morning (7:30am)' }, { label: 'Severity', value: '2/5' }, { label: 'Context', value: 'Poor sleep (2/5), dinner at 9pm, coffee before food, low energy' }], note: 'Even without a heavy meal, eating at 9pm and sleeping poorly can leave you with reflux by morning — especially with morning coffee first.' } },
      ],
    },
    {
      id: String(d('2026-04-20T07:00:00')),
      symptom: 'silent acid reflux',
      timestamp: d('2026-04-20T07:00:00'),
      onset_category: 'just_now',
      summary: 'Symptom: Silent acid reflux, Started: Morning (7am), Severity: 3/5, Context: Late snack (11pm), late bedtime (midnight), sleep 3/5, throat burning on waking, low energy',
      messages: [
        { role: 'user', content: 'silent acid reflux' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '3 out of 5' },
        { role: 'assistant', content: 'What time did you go to bed, and did you eat close to bedtime?' },
        { role: 'user', content: 'Bed around midnight, had a snack at 11pm' },
        { role: 'assistant', content: 'Sleep quality? 1–5?' },
        { role: 'user', content: '3 out of 5' },
        { role: 'assistant', content: 'Anything else that might be related?' },
        { role: 'user', content: 'Woke up with a throat burning feeling and low energy' },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Silent acid reflux' }, { label: 'Started', value: 'Morning (7am)' }, { label: 'Severity', value: '3/5' }, { label: 'Context', value: 'Late snack (11pm), late bedtime (midnight), sleep 3/5, throat burning on waking, low energy' }], note: 'Eating close to bedtime gives the stomach less time to settle before lying down — even a snack before midnight can trigger morning reflux.' } },
      ],
    },
    {
      id: String(d('2026-04-18T07:15:00')),
      symptom: 'silent acid reflux',
      timestamp: d('2026-04-18T07:15:00'),
      onset_category: 'just_now',
      summary: 'Symptom: Silent acid reflux, Started: Morning (7:15am), Severity: 2/5, Context: Poor sleep (2/5), ear pressure on waking, coffee before food, typical morning pattern',
      messages: [
        { role: 'user', content: 'silent acid reflux' },
        { role: 'assistant', content: 'Severity on a scale of 1–5?' },
        { role: 'user', content: '2 out of 5' },
        { role: 'assistant', content: 'Morning episode — how was sleep, and did you wake up with any throat or ear sensation?' },
        { role: 'user', content: 'Sleep was rough, 2/5. Woke up with ear pressure too.' },
        { role: 'assistant', content: 'Coffee before eating this morning?' },
        { role: 'user', content: 'Yes, always' },
        { role: 'assistant', content: 'Anything else you think might be related?' },
        { role: 'user', content: 'Not particularly, just the usual morning routine' },
        { role: 'assistant', summary: { fields: [{ label: 'Symptom', value: 'Silent acid reflux' }, { label: 'Started', value: 'Morning (7:15am)' }, { label: 'Severity', value: '2/5' }, { label: 'Context', value: 'Poor sleep (2/5), ear pressure on waking, coffee before food, typical morning pattern' }], note: 'The combination of reflux and ear pressure on waking is a recognized silent reflux pattern — the acid may be reaching higher than just the esophagus.' } },
      ],
    },
  ]

  const rows = logs.map((log) => ({ ...log, user_id: userId }))
  const { error } = await supabase.from('logs').upsert(rows)
  if (error) throw error
  return logs.length
}
